import Capacitor
import UIKit

/// The app's bridge controller, which exists only to register `ShareIntakePlugin`.
///
/// Capacitor auto-registers exactly two kinds of plugin: its own built-ins, and
/// whatever `cap sync` writes into `capacitor.config.json` as `packageClassList`
/// - and that list is generated from npm packages. A plugin that lives in the
/// app target, as this one does, is in neither set, so without this the bridge
/// never learns about it: `isPluginAvailable('ShareIntake')` comes back false
/// and `drainPendingShares()` quietly returns nothing at all.
///
/// Registering here rather than in `capacitor.config.json` is deliberate - that
/// file is regenerated by every `cap sync` and any edit to it would be lost.
///
/// Add this file to the **App** target only, and keep `Main.storyboard`
/// pointing its view controller at this class rather than at
/// `CAPBridgeViewController`.
class MainViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginInstance(ShareIntakePlugin())
    }
}
